[[build.buildpacks]]
id = "paketo-buildpacks/nodejs"

[[build.buildpacks]]
id = "paketo-buildpacks/web-servers"

[[build.env]]
BP_NODE_VERSION = "20.x"
BP_WEB_SERVER = "nginx"
BP_WEB_SERVER_ROOT = "_static"
BP_NODE_RUN_SCRIPTS = "export"
DATABASE_URL = "postgres://tpa:tpa@postgres:5432/tpa"
DATABASE_POOL_MAX = "10"
DATABASE_SSL = "false"
NEXT_PUBLIC_SUPABASE_BUCKET = "service-images"
SUPABASE_SAVE_CONTACT_FUNCTION_URL = "https://kagbqkivpimlhhcvhmry.supabase.co/functions/v1/save-contact"
