[[build.buildpacks]]
id = "paketo-buildpacks/nodejs-legacy"

[[build.buildpacks]]
id = "paketo-buildpacks/web-servers"

[[build.env]]
BP_NODE_VERSION = "18.x"
BP_WEB_SERVER = "nginx"
BP_WEB_SERVER_ROOT = "build"
BP_NODE_RUN_SCRIPTS = "build"
