create table if not exists analytics_logs (
  id bigint generated by default as identity primary key,
  event text not null,
  url text,
  user_agent text,
  data jsonb,
  created_at timestamptz not null default now()
);
