static_sites:
  - name: theprojectarchive
    source_dir: /
    build_command: "npm ci && npm run build"
    # Next.js generates static files in the "out" directory.
    output_dir: out
    buildpacks:
      - paketo-buildpacks/nodejs-legacy
      - paketo-buildpacks/web-servers
    environment_slug: node-js
    routes:
      - path: /
