services:
  - name: theprojectarchive
    source_dir: /
    build_command: npm ci && npm run export
    run_command: node server.js
    environment_slug: node-js
    instance_size_slug: basic-xxs
    instance_count: 1
    http_port: 8080
    routes:
      - path: /
  - name: api
    source_dir: /
    build_command: npm ci
    run_command: node server.js
    environment_slug: node-js
    instance_size_slug: basic-xxs
    instance_count: 1
    http_port: 8080
    routes:
      - path: /api
functions:
  - name: hello
    source_dir: functions/hello
    routes:
      - path: /hello
