services:
  - name: theprojectarchive
    source_dir: /
    environment_slug: node-js
    instance_size_slug: basic-xxs
    instance_count: 1
    build_command: "npm ci && npm run build"
    run_command: "npm start"
    http_port: 3000
    routes:
      - path: /
