static_sites:
  - name: theprojectarchive
    source_dir: /
    build_command: "npm ci && npm run build"
    output_dir: "_static"
    buildpacks:
      - paketo-buildpacks/nodejs-legacy
      - paketo-buildpacks/procfile
      - paketo-buildpacks/web-servers
    environment_slug: node-js
    routes:
      - path: /
      - source: /*
        destination: /index.html
        status_code: 200
