static_sites:
  - name: theprojectarchive
    source_dir: /
    build_command: npm --prefix next-app run build
    output_dir: next-app/out
    buildpacks:
      - paketo-buildpacks/nodejs-legacy
      - paketo-buildpacks/web-servers
    environment_slug: node-js
    routes:
      - path: /
      - source: /*
        destination: /index.html
        status_code: 200
