apiVersion: apps/v1
kind: Deployment
metadata:
  name: tpa-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tpa-site
  template:
    metadata:
      labels:
        app: tpa-site
    spec:
      containers:
        - name: tpa-site
          image: ${IMAGE}
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: postgres-secret
          env:
            - name: DATABASE_URL
              value: postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/$(POSTGRES_DB)
            - name: DATABASE_POOL_MAX
              value: "10"
            - name: DATABASE_SSL
              value: "false"
          resources:
            # Adjust requests/limits based on expected load
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          livenessProbe:
            # Probe root path to ensure web server responds
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
