apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tpa-site
spec:
  rules:
    - host: example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tpa-site
                port:
                  number: 80
