name: Deploy Preview

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - uses: digitalocean/action-doctl@5727c67aa3c2c34ae9462d5a0ecfea8a1b31e5ce # v2
        with:
          token: ${{ secrets.DO_API_TOKEN }}
      - name: Deploy preview app
        run: |
          doctl apps create --spec <(sed "s/name: theprojectarchive/name: theprojectarchive-pr-${{ github.event.number }}/" .do/app.yaml)
